stages:
  - build


build:
  image: docker:stable-dind
  stage: build
  services:
    - docker:dind
  before_script:
    - echo $HUB_PASSWORD | docker login -u $HUB_USERNAME --password-stdin
  script:
    - docker build -t mrlotfi/gquery:latest .
    - docker push mrlotfi/gquery:latest